kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: songsingress
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    nginx.ingress.kubernetes.io/rewrite-target: '/$2'
  labels:
    app.kubernetes.io/part-of: 'backend'
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: songs-api-service
            port:
              number: 80
        pathType: Prefix
        path: /api(/|$)(.*)
