GET http://localhost:3000/api/songs HTTP/1.1
Accept: application/json

### Add a Song

POST http://localhost:3000/api/songs HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "title":"Down by the River",
  "artist": "Neil Young",
  "album": "Harvest"
}
